# Generated by Django 4.1 on 2024-11-09 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GFSystem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('carga_horaria', models.IntegerField()),
                ('dias_semana', models.CharField(max_length=30)),
                ('notes', models.TextField(max_length=1000)),
            ],
        ),
        migrations.DeleteModel(
            name='disciplina',
        ),
    ]
