# Generated by Django 4.1 on 2024-11-19 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GFSystem', '0002_materia_delete_disciplina'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='faltas',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='materia',
            name='notes',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
