# Generated by Django 4.2.16 on 2024-11-19 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GFSystem', '0004_disciplina_delete_aluno_remove_materia_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materia',
            name='dias_semana',
            field=models.CharField(max_length=100),
        ),
    ]
