# Generated by Django 4.2.16 on 2024-11-19 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GFSystem', '0005_alter_materia_dias_semana'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Disciplina',
        ),
    ]
