# Generated by Django 4.2.16 on 2024-11-19 18:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('GFSystem', '0006_materia_descricao_delete_disciplina'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materia',
            options={'verbose_name': 'Matéria', 'verbose_name_plural': 'Matérias'},
        ),
        migrations.AlterField(
            model_name='materia',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materias', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='materia',
            name='descricao',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='materia',
            name='dias_semana',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='materia',
            name='faltas',
            field=models.IntegerField(),
        ),
    ]
