# Generated by Django 4.2.16 on 2024-11-28 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GFSystem', '0010_alter_materia_dias_semana_periodo_unique_periodo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materia',
            name='periodo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='GFSystem.periodo'),
        ),
    ]
