# Generated by Django 4.2.16 on 2024-11-28 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GFSystem', '0011_alter_materia_periodo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materia',
            name='descricao',
        ),
    ]
