# Generated by Django 4.2.16 on 2024-12-03 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GFSystem', '0015_materia_oculto'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='finalizado',
            field=models.BooleanField(default=False),
        ),
    ]
