# Generated by Django 4.2.16 on 2024-12-04 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GFSystem', '0018_userprofile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materia',
            name='semestre',
            field=models.CharField(choices=[('1', '1º Semestre'), ('2', '2º Semestre')], default='1', max_length=1),
        ),
    ]
